#!/bin/sh
{
  echo "====="
  echo "MONIT-WRAPPER date"
  date
  echo "MONIT-WRAPPER env"
  env
  echo "MONIT-WRAPPER $@"
  $@
  R=$?
  echo "MONIT-WRAPPER exit code $R"
  echo "====="
} >>/tmp/monit.log 2>&1
